### ISSUE TITLE
Expiration date not return with a correct value

### ISSUE THREAD

**Issue by eldontc** [jwtk/jjwt#106]
Class: JwtMap
Method: 

`
 ```
protected static Date toDate(Object v, String name) {
        if (v == null) {
            return null;
        } else if (v instanceof Date) {
            return (Date) v;
        } else if (v instanceof Number) {
            long seconds = ((Number) v).longValue();
            long millis = seconds * 1000;
            return new Date(millis);
        } else if (v instanceof String) {
            long seconds = Long.parseLong((String) v);
            long millis = seconds * 1000;
            return new Date(millis);
        } else {
            throw new IllegalStateException("Cannot convert '" + name + "' value [" + v + "] to Date instance.");
        }
    }
```
`
When the v instanceof Number is true, the value of seconds is already in mills, then the seconds * 1000 multiply 1000 to milliseconds, cause date to go to long future. :)

**Comment by josebarrueta** [comment]
Hi @eldontc,

The reason to multiply the Number by 1000, is because the ```exp```, ```nbf``` and ```iat``` [claims]((https://tools.ietf.org/html/rfc7519#page-10) per the JWT spec must be ```[NumericDate](https://tools.ietf.org/html/rfc7519#page-6)```, which also by the spec is defined by the number of seconds since epoch.

Since JJWT complies the spec, it assumes all values are already given in seconds and therefore we convert the value to milliseconds before being transformed to Java Dates.

HTH!

**Comment by lhazlewood** [comment]
Closing this issue since the JWT spec requires timestamp values to be in seconds, not milliseconds, but please feel free to re-open if you believe a change should be made.
