### ISSUE TITLE
Verify Signature client side

### ISSUE THREAD

**Issue by GuillaumeUnice** [jwtk/jjwt#114]
Hi, I want to know if exist a JS library in order to verify client side the JWT generate by JJWT. I see you have develop NJWT but I would like verified signature client side? Do you know if it’s possible with JJWT?

Thanks for your help!

**Comment by lhazlewood** [comment]
The best thing to do here is to create a JWS (signed JWT) on the server side using a private key and let the client tier use the corresponding public key to verify the signature.  I don't know if NJWT can do that yet, @robertjd ?  If not, there are probably other JS libraries that support rsa public key signature validation, but I personally don't know that landscape well enough to make a recommendation.

**Comment by GuillaumeUnice** [comment]
The problem is here, I test jsrasign and some other but the format of public key provide by JJWT not match with other library :s...

**Comment by lhazlewood** [comment]
Most JavaScript libraries I've seen fail tremendously on representing cryptography concepts correctly, but this has nothing to do with JJWT, and the JJWT maintainers don't have the time to see if other language libraries work correctly according to the JWT RFC specifications.

Because of this, I'm closing this issue as it is unrelated to JJWT.  If you have an issue related to the JJWT library itself or using JJWT within a JVM, or you believe you have found a bug, please feel free to create a new ticket.
