### ISSUE TITLE
JwtMap.toDate method requires seconds

### ISSUE THREAD

**Issue by sashu** [jwtk/jjwt#122]
`else if (v instanceof Number) {
            long seconds = ((Number) v).longValue();
            long millis = seconds * 1000;
            return new Date(millis);
        }`

The claim has value new Date() and is parsed as Number in Map and the number is in millis so no need to multiply the millis to 1000 it should not be presumed that he number value will be coming in seconds always. Since we are handling dates here dates in number always gets converted to millis.

**Comment by lhazlewood** [comment]
Hi @sashu,

I'm afraid this statement is incorrect:

> it should not be presumed that he number value will be coming in seconds always.

The JWT RFC specification *requires* datetimes to be represented in seconds since epoch, never milliseconds.  See the `NumericDate` definition here:

https://tools.ietf.org/html/rfc7519#page-6

That said, I'll leave this ticket open as a reminder to put a code comment in that section of the code so that other people in the future know why it must be in seconds.

If you have any suggestions of how to have JJWT work with milliseconds - while still being specification compliant on the number that is represented in the JWT claims object - please add your thoughts here and/or open a Pull Request containing your suggested implementation.

**Comment by lhazlewood** [comment]
Commented via commmit  https://github.com/jwtk/jjwt/commit/af01cca9224371012f9240c756a6a8ecbf606074
