### ISSUE TITLE
activity-based expiration vs issuing time-based expiration

### ISSUE THREAD

**Issue by afattahi54** [jwtk/jjwt#129]
In a typical web base application, setting the session time out, for example to 6, means that the session is valid if user does not send any request in 6 minutes.

Well, according to above definition, is it possible that I can set the expiration time base on user activity for a JWT token not a certain time?!

Does "jjwt" implement this or I should handle it myself ?

**Comment by lhazlewood** [comment]
Hi @afattahi54 

JJWT's scope is currently focused *only* to the JWT RFC specifications.  You might think of it as a library and not a framework.

You can use JWTs for things like session management (and many other things), but because the JWT specifications do not propose algorithms specifically for application session management, JJWT does not address such concerns.  You must implement that yourself.

The good news is that it is common and usually simple to use JWTs for application session management - OAuth2 is one such approach.  Another approach is to store a JWT in HTTP-only/secure-only cookies and create a new JWT with an updated `exp` field value on every response - that will always 'extend' the life of the JWT and will automatically expire after user inactivity.  There are other approaches too.

You might find this article on [Where to Store your JWTs](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage) useful.

I hope that helps!

**Comment by lhazlewood** [comment]
Closing since there is no work to be done in the JJWT project.  Please use StackOverflow (with the `jjwt` tag) for general questions.  Thanks!
