### ISSUE TITLE
Old Token not getting expired when a new Token is generated before its expiry date

### ISSUE THREAD

**Issue by safvan-elitecore** [jwtk/jjwt#139]
Hello,
Following is the sequence:
- Generate a Token with expiry date as 30 minutes from current time.
TOKEN 1: String authToken = Jwts.builder().setSubject(username).setExpiration(expiryDate).signWith(SignatureAlgorithm.HS512, key).compact();
- After 15 minutes, generate another Token with same subject.
TOKEN 2: String authToken = Jwts.builder().setSubject(username).setExpiration(expiryDate).signWith(SignatureAlgorithm.HS512, key).compact();
- Validate TOKEN 1. Its get validated successfully.
- Validate TOKEN 2. Its get validated successfully.

Expected Behavior:
- When TOKEN 2 is generated with same subject then the older token (TOKEN 1) should not get validated successfully and token expired exception should be thrown.

**Comment by bhowell2** [comment]
@safvan-elitecore,

This is expected behavior on YOUR part, but NOT expected behavior of JWTs. One of the drawbacks with JWTs is invalidating them. The only things that will invalidate a JWT are if it is expired or the signature doesn't checkout. If you're wanting to invalidate them with anything other than time expiration, you're basically getting into tracking state and must store which tokens are invalidated in a database or somewhere. If you allow the user to be logged in with the JWT, but they change their password while the JWT is still valid and someone else has this JWT, then you won't be able to invalidate the rogue user's JWT (without some type of state tracking) until that JWT has expired, even though the user has changed their password.

I'd suggest using a smaller expiration time if you need them to be invalidated frequently. 
For example: if you expect users in your application to use the app in batches (i.e. most requests will happen within 15 mins and then they have some downtime before they come back to it) then set that expiration to be 15 mins. If the user is continuing to use the app after 15 mins, check to ensure that the user hasn't changed their password (use a login cookie or something) and then resign the JWT and give them another 15 mins or something. I wouldn't just assume that the user's JWT hasn't been intercepted in that 15 mins though - or else you're potentially revalidating a rogue user's JWT. (Stormpath has an article on where/how to store JWTs: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage).

You should still see that the above approach would not be foolproof and someone could still act as a user even though their password changed if the JWT hasn't expired. You can still reduce database trips with JWTs if you can find an acceptable expiration tolerance (maybe it's only 1 minute, but if your users are making many requests in that 1 minute, it is still worth it.)

**Comment by lhazlewood** [comment]
Closing this ticket as this is not something any JWT library can solve as described by @bhowell2
