### ISSUE TITLE
Can not set Expired Date or Revoke Token

### ISSUE THREAD

**Issue by KNIGHTMASTER** [jwtk/jjwt#201]
i am currently using jjwt for my application.
I wonder how to revoke token or setExpirationDate to make it Expired.
I've tried like below, but not working
`
public void setTokenToBeExpired(String token) {
Claims claims = this.getClaimsFromToken(token);
		System.err.println("Expiration "+claims.getExpiration());
		Date reverseExpiration = Date(getCreatedDateFromToken(token).getTime() - 3600 * 1000);
		System.err.println("Expiration set To "+reverseExpiration);
		claims.setExpiration(reverseExpiration);
	}
`

Any help please...

**Comment by prateeknischal** [comment]
Token based authentication does not support revocation inherently. The main motive behind token based auth was to remove token store (hence signed to prevent tampering). Even if you change the expiration, you cannot assure that the client will not use the original token that still has time left.

The max you can do is to have lower validity period and then create a dynamic blacklist of revoked tokens in cache and clear the token from cache when the token expires. This should be efficient as user logging out is a less frequent event. The maximum time for a cache is the expiration time of the token.

**Comment by lhazlewood** [comment]
Compact JWTs are immutable.  You can't change them otherwise a new signature would be required, which does not equal the existing/previous signature.

When it comes to using JWTs for Token authentication - this is almost always achieved using expiration as @prateeknischal indicated or via a blacklist database (or cache) with entry TTL that indicates that particular JWT (e.g. the JWT's `kid` value) is invalid.

Just a friendly note:  GitHub Issues are used to track actionable work to change the JJWT codebase.  Please ask usability questions on StackOverflow using the `#jjwt` tag.  Thanks!
