### ISSUE TITLE
Support for headless tokens

### ISSUE THREAD

**Issue by skuzzle** [jwtk/jjwt#233]
Hi all,

is it possible to generate/parse headless tokens or would you consider this a useful enhancement? In my opinion headless tokens are a nice approach for saving some bandwidth when your application does not need to handle dynamic header information but instead use some static hardcoded defaults.

**Comment by lhazlewood** [comment]
To the best of my knowledge, headless tokens are not allowed per [RFC 7519](https://tools.ietf.org/html/rfc7519), specifically [Section 7.2, Validating a JWT](https://tools.ietf.org/html/rfc7519#section-7.2).  All JWSs and JWEs have a header, and if you don't need any security whatsoever, you'd still need an [Unsecured JWT](https://tools.ietf.org/html/rfc7519#section-6) with a header of `{"alg":"none"}`.

This is required because, without it, it's not possible for a JWT parser to know which security guarantees to enforce, if any.  In other words, a JWT is either unsecured or secured, and secured always requires a header, but unsecured also requires a header to say "hey, this is unsecured, and that is ok".

Without a header at all, the JWT parser can't know what security guarantees to enforce which is insecure.

Feel free to comment or re-open if you're confident this interpretation of the specification is incorrect.  Thanks for the issue!

**Comment by skuzzle** [comment]
Right, my suggestion is not part of the specification and should not be given attention if strict RFC compatibility with no extra features is desired.
However, my point is, that headless tokens are of course technically possible and also provide some advantages (see also bullet 4. at https://dev.to/neilmadden/7-best-practices-for-json-web-tokens).
If, for example, my app only needs to verify tokens that it issued itself, there is no need to name the used  algorithm in the header.
I do understand this sounds a bit hacky, but bearing in mind the security issues mentionend in referenced blog post, this might still be a useful enhancement to the library (although one could as well post/pre process the token to remove/add the head as suggested in the blog post)
