### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by marcelstoer** [jwtk/jjwt#247]
I didn't come here to rant about your code but allow one question. Is it a security feature to _not_ implement any logging for an application?

Just today I was analyzing your ["JWT signature does not match locally computed signature..." exception](https://github.com/jwtk/jjwt/blob/master/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java#L354) in my application. Rather than poking around in an unfamiliar code basis I wanted to turn up the log level for the library first. When this yielded no results I cloned this repo and ran `grep -ri log *` which left me totally puzzled. Exclusions for commons-logging in the POM, ok, but Logback only in test scope? I'm confused.

Btw, DefaultJwtParser#parse(java.lang.String) _is_ an enormous complexity monster of 200+ lines 😉

**Comment by lhazlewood** [comment]
We've been thinking about adding it before the 1.0 release, but it would also add a dependency that maybe some don't want.  

FWIW, this issue is the first we've ever seen from anyone asking about logging (not that isn't important) - just an indicator of want vs. need.  In other words, we're most likely to focus on being spec compliant first and then add features the community is most vocal about.

Can you give us an idea of the kinds of things you'd like to see logged?  That would be helpful in actually implementing logic instead of "hrm - I dunno if this is useful, so I'll log just in case" and bloating the codebase.  I've also changed the issue name to something more... constructive ;)

**Comment by marcelstoer** [comment]
> it would also add a dependency that maybe some don't want

You could use JUL.

> we're most likely to focus on being spec compliant first and then add features the community is most vocal about

Sensible approach, I agree.

> Can you give us an idea of the kinds of things you'd like to see logged?

I don't want to start a flame war about logging best practices or logging guidelines. Lots of smarter folks (smarter than I that is) have done that before in other corners of the Internet.

Take my "JWT signature does not match locally computed signature..." case. I would have like to know
- what was the JWT signature
- what was the locally computed signature
- what was the input for the locally computed signature
- what was the algorithm for the locally computed signature

You could pack all of that into the exception message, IMO a valid alternative.

**Comment by jansohn** [comment]
Why not use `SLF4J` and let the users decide whether they want logging or not?

https://www.slf4j.org/faq.html#when

**Comment by lhazlewood** [comment]
If we add logging, it will most definitely be SLF4J.  That allows you to plug in any logging provider implementation you desire.

Thanks for the issue!  We'll keep this open to retain a log/list of the types of logging requested by the community until we're ready to force a dependency on everyone.
