### ISSUE TITLE
some question with  rsa encryption in ‘signWith’ api

### ISSUE THREAD

**Issue by itfinally** [jwtk/jjwt#271]
Hello, I have a question of 'signWith' api.
In rsa algorithm, it is encrypted message with private key ?

Because I read a lot of blog and they said 'encrypted with public key' / 'decrypt with private key', and the public key can given anyone.   = 。=

But I got the exception when I encrypted with public key:
```
String jwt = Jwts.builder()
                .setClaims( body )
                .signWith( alg, publicK ) // public key
                .compact();

        Claims info = Jwts.parser()
                .setSigningKey( privateK ) // private key
                .parseClaimsJws( jwt )
                .getBody();
```
This is the message( RSA signatures must be computed using an RSA PrivateKey ??? ):
```
Exception in thread "main" java.lang.IllegalArgumentException: RSA signatures must be computed using an RSA PrivateKey.  The specified key of type sun.security.rsa.RSAPublicKeyImpl is not an RSA PrivateKey.
	at io.jsonwebtoken.impl.crypto.RsaSigner.<init>(RsaSigner.java:36)
	at io.jsonwebtoken.impl.crypto.DefaultSignerFactory.createSigner(DefaultSignerFactory.java:43)
```

But it work when I swap the key...
Am I wrong ?

**Comment by jansohn** [comment]
It's always sign with private key and verify with public key!

**Comment by lhazlewood** [comment]
@itfinally the blog article you read is incorrect.  Signatures using keypairs are _always_ created/signed with the _private_ key, and verified with the public key, never the other way around. In fact the exception message tells you that a public key isn't valid for creating signatures:

> RSA signatures must be computed using an RSA PrivateKey.  The specified key of type sun.security.rsa.RSAPublicKeyImpl is not an RSA PrivateKey. 

Think about this for a minute - if it where the other way around, anyone with the public key (i.e. everyone because it's 'public') would be able to spoof your identity and create signatures as if they were you. 

Cryptographic signatures, just like your hand-written signature, should be 'create-able' by one and only one person or entity (the private key holder).  Public key holders can then trust that a verified signature came from you and only you.

**Comment by itfinally** [comment]
I used to pay attention to encryption.... = =||
Thank to show me the difference between encryption and signature.
It help for me.
