### ISSUE TITLE
Why allowedClockSkewMillis must be > 0?

### ISSUE THREAD

**Issue by ex34toway** [jwtk/jjwt#290]
1. Fine,if i impl just want skew before the now time expire jwt，set allowedClockSkewMillis < 0,but 
final boolean allowSkew = this.allowedClockSkewMillis > 0 ==> allowSkew  = false,that will not be change the max (Date max = allowSkew ? new Date(maxTime) : now)。So,I think，
boolean allowSkew = this.allowedClockSkewMillis > 0 ==> boolean allowSkew = this.allowedClockSkewMillis != 0 ,and setAllowedClockSkewSeconds can set a negative value indicate before secods exp。

**Comment by lhazlewood** [comment]
You can specify any value you wish - negative, positive or `0`, and JJWT will always use the greater of `0` or your value as the actual value.  Negative clock skew does not make sense because the value is only relevant for times *after* the `exp` claim field - i.e. always time _added_ to the `exp` value.  A negative value essentially means "no skew necessary".

Finally, a friendly reminder: JJWT's GitHub issues are for actionable work that requires changes to the JJWT codebase. Please use StackOverflow with the `#jjwt` tag for usability/help questions. Thanks!

**Comment by ex34toway** [comment]
Ok.I've got it.Thank you.
