### ISSUE TITLE
Creating token for ES256 Algorithm throws IllegalArgumentException: Key bytes may only be specified for HMAC signatures.

### ISSUE THREAD

**Issue by sscarduzio** [jwtk/jjwt#326]
Hi guys, I have this piece of code, that works with algorithm "HS256", but throws this exception with "ES256" which is needed if we want to use [Google Cloud IAP](https://cloud.google.com/iap/docs/signed-headers-howto#iap_validate_jwt-java).

The exception:

```
java.lang.IllegalArgumentException: Key bytes may only be specified for HMAC signatures.  If using RSA or Elliptic Curve, use the signWith(SignatureAlgorithm, Key) method instead.

	at io.jsonwebtoken.lang.Assert.isTrue(Assert.java:38)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:96)
```

The code that throws the exception:
```java
    JwtBuilder builder = Jwts.builder()
      .setSubject("test")
      .signWith(SignatureAlgorithm.valueOf("ES256"), key.getBytes());
    claims.forEach(builder::claim);
```

I didn't find any example on how to create a Key object given byte array or string representing the key that comes from my configuration file.

Please advise

**Comment by lhazlewood** [comment]
You need to find out how to convert your key in your configuration file to an elliptic curve `PrivateKey` instance and use that instance as the argument to the `signWith` method:

```java
PrivateKey privateKey = loadEcPrivateKeyFromConfiguration(); //implement me
JwtBuilder builder = Jwts.builder()
      .setSubject("test")
      .signWith(SignatureAlgorithm.valueOf("ES256"), privateKey);
    claims.forEach(builder::claim);
```

Since I don't know the format or the content encoding of the key in configuration, I couldn't tell you how to convert it to an EC PrivateKey instance.  Here is a StackOverflow answer that shows an example, but only if your config file is formatted the same way:

https://stackoverflow.com/questions/41927859/how-do-i-load-an-elliptic-curve-pem-encoded-private-key

Just a friendly reminder: JJWT's GitHub issues are for actionable work that requires changes to the JJWT codebase.  Please use StackOverflow with the `#jjwt` tag for usability/help questions.  Thanks!
