### ISSUE TITLE
remove slf4j dependency?

### ISSUE THREAD

**Issue by arvinsuresh** [jwtk/jjwt#34]
Will it be possible to avoid dependency on slf4j logger? Looks like the only class using it is io.jsonwebtoken.lang.Classes?
I'm trying to use this in a WAS TAI which requires me to deploy jjwt and its dependent libraries so it is loaded as a WAS extension, which then affects any application specific class loaders trying to load their slf4j.

I like that jjwt has very few dependencies, seems like it might be possible to avoid slf4j also.

**Comment by pglezen** [comment]
+1
Since JJWT is a library that ideally would be referenced from a wide variety of execution contexts (JEE, standalone, Spring containers, OSGi containers (ok, OSGi doesn't have this problem)), dependencies should be kept to an absolute minimum.  If SLF4J was embedded everywhere in JJWT, I would wipe my brow and bear it.  But it seems that by simply (pun intended) logging to the JUL Loggers in the one class mentioned by @arvinsuresh , we could avoid yet another dependency.

Full disclosure: I worked with Arvin for a few months last Spring where we used JJWT.  So my post stems from a common issue we both experienced on the same project task.  But I expect this issue to reoccur with other teams I encounter.  I'm a big fan of JJWT and nixing this extra dependency would really help to spread it.

**Comment by lhazlewood** [comment]
Yeah, this was an artifact from a copy-n-paste operation long ago.  I'm happy to remove it since it's not prolific in JJWT and only used in one class.  Thanks for the issue!

**Comment by mattblang** [comment]
+1
Android users try to stay under a function limit of 65k, so removing unnecessary dependencies would be nice.

**Comment by lhazlewood** [comment]
Resolved by PR #41.  Will be released in 0.6.
