### ISSUE TITLE
parseClaimsJws may throw something other than SignatureException

### ISSUE THREAD

**Issue by t0b0** [jwtk/jjwt#349]
According to README.md, the recommended way to do signature verification is the following: 
```java
try {
    Jwts.parser().setSigningKey(key).parseClaimsJws(compactJws);
    //OK, we can trust this JWT
} catch (SignatureException e) {
    //don't trust the JWT!
}
```
But this is insufficient as the following example demonstrates:

```java
String key_b64 = "m+wtZPGdFE+9PdZeDVKeg5qPl+y2UiszFIMlYm8VwSCRq1WFTlJTL0VimsAau54fE6NIjP5haHANuYrXePHciw==";

// maliciously crafted JWT with empty signature
String jwt_fake = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJKb2UifQ.";

Key key = new SecretKeySpec(Base64.getDecoder().decode(key_b64), "HmacSHA256");

try {
    Jwts.parser()
            .setSigningKey(key)
            .parseClaimsJws(jwt_fake);

    //OK, we can trust this JWT
    System.out.println("Hack Successful");
} catch (SignatureException e) {
    //don't trust the JWT!
    System.out.println("Hack Failed");
    e.printStackTrace();
} catch (Exception e){
    // This is the path that will be actually taken. 
    System.out.println("Hack Semi-Successful");
    e.printStackTrace();
}

```

**Comment by lhazlewood** [comment]
Hi there!  

The readme is just a simple example for quickstart/demonstration purposes, not recommended usage.  It is not representative of exhaustive-path execution, otherwise the readme would be way too long.  Readmes in general, as I see them, are not to be used as the canonical source for definitive information - they're just there to whet your appetite and get you started quickly.

In this particular case, the existing readme specifically cites `But what if signature validation failed?` before showing its example.  The code snippet above doesn't include a signature, so the readme example still makes sense (to me at least) - that is, you can't have a SignatureException if there is no signature...

Additionally, catching just `Exception` may not be recommended depending on the developer's preferences - it hides any exceptions that might exist due to library or JVM failure.  That's the reason why JJWT has a rich set of Exceptions - so you can decide what you care about and what you don't and react accordingly.  At the very least `JwtException` is the root of all of JJWT's exception hierarchy, as opposed to the JVM-catch-all `Exception`.

In all cases, the JavaDoc is the authoritative source for API usage, inputs, outputs, expectations, and side effects, and `JwtParser#parseClaimsJws` does indeed show multiple exception possibilities.  Developers *must* know APIs they're using and what the edge-cases are, and that's why we spend so much time on JavaDoc.  Readmes are never sufficient replacements for the API docs IMO.

So, back to this particular issue - does this ticket represent actionable work to change JJWT's codebase?  If so, what is the change?  Note that I prefer that the Readme is not canonical documentation - that's what the JavaDoc is for, otherwise we just duplicate efforts.  Thanks!

**Comment by t0b0** [comment]
Hi Les,
I see your points. I've seen examples in the wild where developers were using `Jwts.parser().setSigningKey(key).parseClaimsJws(jwt_string);` and then only checked for the `SignatureException`, which led to vulnerabilities. Probably because they copied the snipped from the README.md. I think their wrong assumption was that when you do `setSigningKey`, the library should always expect a signature and give you a `SignatureException` if there isn't one. 
I think it's important to have secure-by-default APIs and reduce the chance of developers misusing an API as much as possible. At the very least, it'd be good if we change the README to make clear that SignatureException is not the only exception you have to catch when you're expecting a valid signature.

**Comment by lhazlewood** [comment]
Also, FWIW (in case anyone else is reading this thread), JJWT's API is definitely secure-by-default.  Not catching a `MalformedJwtException` has no bearing whatsoever on JJWT's security model.

**Comment by lhazlewood** [comment]
Hi @t0b0 

> and then only checked for the SignatureException, which led to vulnerabilities

Can you please clarify these vulnerabilities?  If an exception is uncaught and propagates, the JWT isn't processed, so I don't see what the vulnerability is.

**Comment by lhazlewood** [comment]
Documentation in the latest 0.10.0 release includes multiple **bold** notices on the correct method to use as well as changes the example from `SignatureException` to `JwtException` and also explains the possibility for signature and non-signature-related exceptions.  Thanks for the issue!
