### ISSUE TITLE
Android base64 encoded key validation problem

### ISSUE THREAD

**Issue by tomasklatt** [jwtk/jjwt#479]
Hello, 

I have problem with validation the token i am getting from our API.

When i try to validate the tokenI use this code:

`val claims = Jwts.parser().setSigningKey("KEY_STRING").parseClaimsJws("TOKEN_STRING").body`

but even when jwt.io says it's valid the library throws exception 

` Token Error: io.jsonwebtoken.security.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.`

But when I parse the token string to the jwt.io, then check on the page "Secret base64 encoded" and copy the changed token then it's valid.

Is there any way how to change the token like jwt.io does or the API has to send me token in that way.

I checked some other issues with base64 encoding problems but I didn't find solution that would work for me, so I am sorry if there is solution already.

Thanks for help.

**Comment by tomasklatt** [comment]
Ok, solution is 

`val claims = Jwts.parser().setSigningKey(Base64.encodeToString("KEY_STRING".toByteArray(), Base64.DEFAULT)).parseClaimsJws("TOKEN_STRING").body`

**Comment by lhazlewood** [comment]
`setSigningKey` JavaDoc explains that the string is expected to be Base64-encoded.  FWIW, because of issues like this, that method has been deprecated since 0.10.0 and your compiler will warn you if you use it.  So don't use it 😉 .

Ensure you are using the latest stable `0.10.7` release and use `setSigningKey(Key)` instead.

Also, in the future, please ask questions or for help according to our documentation on [Asking for Help](Please read https://github.com/jwtk/jjwt#help).  We use GitHub Issues only for tracking things that require actionable changes to the JJWT source code.  Thanks!

**Comment by tomasklatt** [comment]
Ok, so proper solution is:

`val claims = Jwts.parser().setSigningKey(Keys.hmacShaKeyFor("KEY_STRING".toByteArray())).parseClaimsJws("TOKEN_STRING").body`

right? Next time I will ask on SO, sorry.
