### ISSUE TITLE
US Export Control rating (ECCN) for jjwt-0.7.0.jar

### ISSUE THREAD

**Issue by rdss12345** [jwtk/jjwt#537]
Sorry to add this as an issue but I raised a Stack Overflow question and it was promptly closed as off-topic.

Ref: jjwt-0.7.0.jar
We are conducting export control checks on software that uses this library and have identified it as potentially containing cryptography.

As the download links for this library are hosted by github can the developers please confirm whether the required notification under the EAR related to open source encryption source code has been made to US Government or advise the grounds why the developers deem such notification isn’t required?

The requirement comes from US EAR legislation and github T&Cs relating to submissions.

"You may not use GitHub in violation of export control or sanctions laws of the United States or any other applicable jurisdiction. You may not use GitHub if you are or are working on behalf of a Specially Designated National (SDN) or a person subject to similar blocking or denied party prohibitions administered by a U.S. government agency. GitHub may allow persons in certain sanctioned countries or territories to access certain GitHub services pursuant to U.S. government authorizations. For more information, please see our Export Controls policy."

https://help.github.com/en/github/site-policy/github-terms-of-service
https://help.github.com/en/github/site-policy/github-and-trade-controls

For background information and some FAQ’s please see
http://www.apache.org/dev/crypto.html
https://www.ecfr.gov/cgi-bin/text-idx?SID=00a8f54989eaf101a84eff3db59ac6e9&mc=true&node=se15.2.742_115&rgn=div88

Many thanks,
Rowland

**Comment by lhazlewood** [comment]
Thanks very much for trying StackOverflow first - it's much appreciated!

JJWT doesn't implement or distribute any crytpographic algorithms - such as ECDSA, RSA, HMAC-SHA digests, etc, nor does it include, embed or distribute any library (such as BouncyCastle) that can perform these operations either.

When JJWT attempts a cryptographic operation, it becomes a client, or consumer or _caller_ of the [Java Cryptography Archicture APIs](https://docs.oracle.com/javase/8/docs/technotes/guides/security/crypto/CryptoSpec.html) that natively exist in the JVM distribution that is running the JJWT bytecode.  It is the JVM - not JJWT - that implements and executes those cryptographic operations.  JJWT just uses these native Java APIs in the manner dictated by the [JWT JWA RFC](https://tools.ietf.org/html/rfc7518).

I am not a lawyer, but it is my understanding that because JJWT doesn't perform these operations - and merely delegates to the JVM to do them - the JJWT project isn't required to notify the U.S. government, and hasn't done so as a result.  The JVM implementation - or any implementation of the actual algorithms - however *is* required to notify the U.S. government if export out of the United States is possible, and I'm reasonably sure the Oracle and OpenJDK teams have already done so. Whether you choose a JVM implementation that has notified the government, or an external JCE provider - like BouncyCastle - is completely orthogonal to and unrelated to JJWT's use and execution.

Since you referred to the Apache crypto page, I can speak to that as well because in addition to being JJWT's primary author, I am also a founder and current PMC Chair of the Apache Shiro project - an Apache library that addresses application security, and which also executes cryptograhic operations in the same manner by delegating to the JVM's native APIs.

The Apache Software Foundation has notified the U.S. government of associated releases, and as a result the Apache Shiro project has been classified as ECCN 5D002.C.1 per it's [README](https://github.com/apache/shiro/blob/master/README):

```
This distribution includes cryptographic software.  The country in
which you currently reside may have restrictions on the import,
possession, use, and/or re-export to another country, of
encryption software.  BEFORE using any encryption software, please
check your country's laws, regulations and policies concerning the
import, possession, or use, and re-export of encryption software, to
see if this is permitted.  See http://www.wassenaar.org for more
information.

The U.S. Government Department of Commerce, Bureau of Industry and
Security (BIS), has classified this software as Export Commodity
Control Number (ECCN) 5D002.C.1, which includes information security
software using or performing cryptographic functions with asymmetric
algorithms.  The form and manner of this Apache Software Foundation
distribution makes it eligible for export under the License Exception
ENC Technology Software Unrestricted (TSU) exception (see the BIS
Export Administration Regulations, Section 740.13) for both object
code and source code.
```

Given that JJWT delegates to the JVM for cryptographic behavior in the same way that Apache Shiro does, JJWT in all likelihood would be classified as ECCN 5D002.C.1 as well (even though we haven't attempted this due to the above reasons).

If you believe this analysis to be incorrect (again, because I'm not a lawyer 😉 ), please have your attorney(ies) reach out to me explaining why and, if warranted, I'd be happy to start the notification process.  Thanks!

**Comment by rdss12345** [comment]
Thank you for your quick response. In summary, we need a US export control licence for our product. In order to gain that we need a rating for the FOSS libraries used by it. We either need to find a rating already provided by a library's authors or get a statement from the authors. As you can imagine there are going to be false positives where we need the author to state that there is no cryptography in the library and that they are exempt. Unfortunately we are not allowed to inspect the code and determine this ourselves. I believe that your post on 4/12/19 in reply to mine provides me with what we need.
Thank you very much.
Best wishes,
Rowland

**Comment by lhazlewood** [comment]
Hi Rowland - I'm glad I could help.  But what reply on 4/12/19?  Do you have a link?

**Comment by rdss12345** [comment]
Hi. it's the one above where you state that;

"JJWT doesn't implement or distribute any crytpographic algorithms - such as ECDSA, RSA, HMAC-SHA digests, etc, nor does it include, embed or distribute any library (such as BouncyCastle) that can perform these operations either.

When JJWT attempts a cryptographic operation, it becomes a client, or consumer or caller of the Java Cryptography Archicture APIs that natively exist in the JVM distribution that is running the JJWT bytecode. It is the JVM - not JJWT - that implements and executes those cryptographic operations. JJWT just uses these native Java APIs in the manner dictated by the JWT JWA RFC."

I think that that statement will be sufficient for the rating agency. If it's not then they will tell me so and I will have to come back to you further.

Best wishes,
Rowland

**Comment by lhazlewood** [comment]
Ah, sorry, my confusion was due to the difference in U.S. dates representations.  I originally thought you were referring to April (4) 12th 2019.  Thanks for clarifying! :smile:
