### ISSUE TITLE
Problem with claims / long values

### ISSUE THREAD

**Issue by annrodrigues** [jwtk/jjwt#541]
I added a claim with the Long type value `"code":26469708576325829` but when it is encoded in the class `DefaultJwtBuilder.java` by the method `base64UrlEncode(Object o, String errMsg)` calling `TextCodec.BASE64URL.encode(bytes)`, it returns a token that the value of the claim is `"code": 26469708576325828`. The only last digit is changed!!!

A simple test:

Map<String, Object> publicClaims = new HashMap<>();
publicClaims.put("code", 26469708576325829L);

ObjectMapper objectMapper = new ObjectMapper();
byte[] bytes = objectMapper.writeValueAsBytes(publicClaims);

String token = TextCodec.BASE64URL.encode(bytes);

Token response is: `eyJzZXNzaW9uX25hbWUiOiJuYW1lIiwiY29kZSI6MjY0Njk3MDg1NzYzMjU4MjksIm5hbWUiOiJhZG1pbiJ9`

If I decode it with TextCodec, the response is correct, like:

String tokenDecoded = TextCodec.BASE64URL.decodeToString(token);

If I use String type, it is correct in the encode and decode!!! But I would like to use the true type Long.

**Comment by lhazlewood** [comment]
Hi there!

JJWT basically just delegates your claims Map to the underlying JSON Marshaller (e.g. Jackson).

Can you please try the same test using just a Map and Jackson and let us know what you find?  If the issue occurs with Jackson or your chosen marshaller, there's not much we can do - it would probably be a setting with the marshaller itself.

For example, see this: https://stackoverflow.com/questions/16052314/how-can-i-force-jackson-to-write-numbers-as-strings-when-serializing-my-objects

Please let us know what you find!

**Comment by lhazlewood** [comment]
P.S. if you find the problem is with Jackson and you want to customize the Jackson ObjectMapper to handle this appropriately, you can use your custom ObjectMapper with JJWT as documented here:
* https://github.com/jwtk/jjwt#json
* https://github.com/jwtk/jjwt#json-jackson

If you find this is something with Jackson and you believe that JJWT's default ObjectMapper should be customized a different way to prevent this from happening, please do let us know here so we can discuss further. Thanks!

**Comment by lhazlewood** [comment]
No follow-up from OP.  This is ultimately a JSON Marshaller setting (e.g. configure using BigInteger when finding large numbers) and likely out of the purview of JJWT.
