### ISSUE TITLE
SignatureException should extend ClaimJwtException

### ISSUE THREAD

**Issue by bmhm** [jwtk/jjwt#544]
Hi,

I think SignatureException could and/or should contain claims.
Rationale: If a signature cannot be validated, this might be a malicious attempt to falsify a jwt. If we do not read the claims, we do not know the user.

This also means that this exception could only be raised if  the claims were parsed first (before the signature is validated). Currently, the signature exception would fail before the Claims are even validated.

**Comment by lhazlewood** [comment]
A signature is not a claim - it's not even in the same JWT string token - and therefore shouldn't extend from `ClaimException`.

> Rationale: If a signature cannot be validated, this might be a malicious attempt to falsify a jwt. If we do not read the claims, we do not know the user.

If signature verification fails, what makes you think the claims are safe to use and that the user field hasn't been manipulated to be someone else?

The _entire point_ of the signature is to ensure that the claims or header has not been manipulated.  If the correct verification key is used and the signature verification fails, that is a clear indication that the header or claims have been manipulated - and therefore should never be trusted/used.

Because of the massive security hole this would open up, I'm sorry, but we have no interest in implementing this.

**Comment by bmhm** [comment]
Hi @lhazlewood 

I understand your point. 
I'd just like to know, if the signature is not correct, which account the attacker tried to log in to (subject).

Isn't that somewhat reasonable?
Of course I'm not trusting it at all.
