### ISSUE TITLE
Why doesn't secret key algorithm matter?

### ISSUE THREAD

**Issue by vprudnikov** [jwtk/jjwt#581]
Hi!

I have a question about `JwtParser`.

How I usually create it:
```
    return Jwts.parser().setSigningKey(BASE64.encode(secretKey));
```

After looking into the source code of JJWT, I modified that line of code to:
```
    return Jwts.parser().setSigningKey(new SecretKeySpec(secretKey.getBytes(), "blablablaAlgorithm"));
```

My test (that calls `jwtParser.parseClaimsJws(token)`) passed but I don't understand WHY.
**Why is there no check in the JJWT library that the _key's algorithm_ matches the algorithm specified in a JWT header?** I just don't expect that the key's algorithm is ignored.

**Comment by lhazlewood** [comment]
```new SecretKeySpec(secretKey.getBytes(), "blablablaAlgorithm")```

The second constructor argument is the [name of the digest algorithm used by the JDK JCA standard]( https://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#provider).

The JWT header algorithm name is the [digest algorithm identifier as specified in the JWA RFC specification](https://tools.ietf.org/html/rfc7518#section-3.1).

These two names - one an RFC name and the other a JDK specification name - are not the same because they come from two different specifications.  When using a JWT-standard algorithm, the name in the JWT header must equal one of the names identified in the JWA RFC.   This is why the value in the jwt header does not equal the one in your `SecretKey` instance.

So, if you don't specify a secret key algorithm, JJWT will automatically choose the strongest algorithm available depending on the size of your SecretKey byte array length as documented here: https://github.com/jwtk/jjwt#jws-create-key.  So your `SecretKey` instance is indeed inspected for algorithm strength per the JWA rfc, just using the JWA-specific algorithm name (and not the JDK algorithm name).

Finally, as a friendly reminder, please use GitHub issues for actionable work to change the JJWT codebase.  For questions, please read https://github.com/jwtk/jjwt#help-questions  Thanks!

**Comment by vprudnikov** [comment]
@lhazlewood thank you for your reply!

I was probably confused by a Javadoc of `setSigningKey` saying:
```
     * <p>Note that this key <em>MUST</em> be a valid key for the signature algorithm found in the JWT header
     * (as the {@code alg} header parameter).</p>
```

So (as you see in my example) I created a `SecretKeySpec` with an arbitrary alg string, and it worked out without any error.

I was surprised that the algorithm in SecretKey was just ignored.

**Comment by lhazlewood** [comment]
Yep, the JWA RFC doesn't "care" about JDK JCA names, so there's no need to raise an error.
