### ISSUE TITLE
expose hash algorithm in SignatureAlgorithm enum

### ISSUE THREAD

**Issue by dirkbolte** [jwtk/jjwt#586]
I'm working on a software in the context of OpenID and need to add code creating and verifying `at_hash` and `c_hash` according to https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken . Instead of having to resolve the algorithm myself it would be great to have this exposed as part of the `SignatureAlgorithm` enum as it already contains all these information. 

e.g. I would write code like this:

```kotlin
val hashName = SignatureAlgorithm.forName(idToken.header.getAlgorithm()).jcaHashName()
val digest = MessageDigest.getInstance(hashName)
```

Along with that, I would expose the algorithm and digest values as well.

Does this fit into this library and would it be ok for me to open a PR for this?

**Comment by lhazlewood** [comment]
I'm a bit confused.  Why not call the `getJcaName()` method on the `SignatureAlgorithm` instance?  I'm sure I'm missing something :-D

**Comment by dirkbolte** [comment]
`getJcaName()` is works for the KeyGenerator of JCA.

For MessageDigest, I have to use the names as of https://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#MessageDigest  - which differ. And I have not found a way provided by JCA to derive one of the other. Is there is though, it would work for me as well. Was thinking about adding some convenience methods though.

**Comment by lhazlewood** [comment]
Ah, I see what you're saying now - thanks for the clarification.

JJWT only computes Macs - essentially authenticated message digests, which always require a key.  It doesn't use `MessageDigest` since message digests do not need keys/authentication (e.g. a file MD5 checksum is a message digest because it doesn't require a key, but a digital signature is a Mac because it requires a key for authenticity).

In this sense, `jcaName` also works for computing macs, not just key generation.  Here's JJWT's current internal implementation for computing a mac:

https://github.com/jwtk/jjwt/blob/c09deaa5f31fb7b3a8184daec4228269942c77a4/impl/src/main/java/io/jsonwebtoken/impl/crypto/MacSigner.java#L64-L66

Additionally, if you look in that same file above on line 48, it just calls `mac.doFinal(data)` where `data` is the byte array for which to compute the mac.

Based on this, JJWT has no need to represent `MessageDigest` JCA algorithm names in its codebase at all, so that probably wouldn't be something we'd want to add since it serves no purpose for JWT requirements.

If I were in a similar situation, I'd probably introduce a mapping class that maps SignatureAlgorithm instances to `MessageDigest` instances to return the appropriate instance.  Or even pass in a `jcaName` value, parse it, strip off the substring(s) that aren't necessary, and use the resulting string as the argument to `MessageDigest.getInstance`.  Or similar.

Hopefully that makes sense!

**Comment by dirkbolte** [comment]
The mapper is what I’m doing now. Was hoping to get around that to have a more save code. Will go with a mapper then.
