### ISSUE TITLE
How to read(decode) a JWS without key

### ISSUE THREAD

**Issue by natehsu** [jwtk/jjwt#612]
Hi,
Can I read(decode) a JWS without any key?
Because I need to get expiration time claim and check it, but I don't have the key.
I can't find the java method in documents.

I would appreciate your help.

**Comment by lhazlewood** [comment]
Just a friendly reminder: JJWT's GitHub issues are for actionable work that requires changes to the JJWT codebase. Please use StackOverflow with the `#jjwt` tag for usability/help questions. Thanks!

This is insecure, so JJWT doesn't support it very easily out of the box because of all the security problems it could cause.

You can do it yourself by taking the middle 'chunk' of the JWS (in between the two periods), and calling `Decoders.BASE64URL.decode(chunk)` to get the JSON and then use Jackson or whatever to turn that JSON string into a Map.
