### ISSUE TITLE
Deprecate JwtParserBuilder#setSigningKey(String)

### ISSUE THREAD

**Issue by horizonzy** [jwtk/jjwt#617]
Hello. I noticed the code:
 ```
    @Deprecated
    JwtBuilder signWith(SignatureAlgorithm alg, String base64EncodedSecretKey) throws InvalidKeyException;
```
in the doc, this api will be removed in 1.0 realease, and recommend user to use 
`JwtBuilder signWith(Key key, SignatureAlgorithm alg) throws InvalidKeyException;` to replace the old api.

so we need to buid the key as follow:
`SecretKey secretKey = Keys.hmacShaKeyFor(Decoders.BASE64.decode(base64EncodedSecretKey));
`

but the code `JwtParserBuilder setSigningKey(String base64EncodedSecretKey);` doesn't deprecated. it will transfer string to base64 byte array by framework. if user use `Keys.hmacShaKeyFor(byte[] bytes)`, but the byte[] not decoded by base64, the error will occur.

**Comment by horizonzy** [comment]
```
@Deprecated
   JwtBuilder signWith(SignatureAlgorithm alg, String base64EncodedSecretKey) throws InvalidKeyException;
```
if this code will removed, maybe ` io.jsonwebtoken.JwtParserBuilder#setSigningKey(java.lang.String)` remove together, let user build the byte[] by hisself, not build byte[] by himself when  signWith(), build byte[] by framework when setSigningKey

**Comment by lhazlewood** [comment]
The `JwtParserBuilder.setSigningKey(String)` should have been deprecated - this was an oversight when we created it and copied over the interface methods from the old setters on `JwtParser`.  `JwtParser` does indeed reflect that the method is deprecated, so it shouldn't be used.

I'll update this issue to reflect that work.  Thanks for reporting it!

**Comment by horizonzy** [comment]
@lhazlewood another question, I notice `io.jsonwebtoken.security.Keys#hmacShaKeyFor(byte [])`, when build the key, it will auto choose algorithm according the byte's length. if we invoke `JwtBuilder signWith(Key key)`, it will use the algorithm in key. but in fact, we can invoke `JwtBuilder signWith(Key key, SignatureAlgorithm alg)`, choose the algorithm by ourselves.
what is the difference between that two way. in other words, which way do you recommend.

**Comment by lhazlewood** [comment]
`signWith(Key, SignatureAlgorithm)` is for cases when you have a key, but you want to override JJWT's heuristics and explicitly choose the signature algorithm.

For example, maybe you have an existing 512-bit secret key.  This would work for `HmacSHA512` algorithms, but it could also be used for `HmacSHA384` and `HmacSHA256`.  Maybe due to the size of the JWT signature, you want to use `HS256` because of the smaller output (I don't recommend this, but there are application or network reasons why this might be necessary).

Or if you have a 4096-bit RSA key, but you only want to use `RS256`:  perhaps the machine that produced the JWT has no cryptography restrictions and can use `RS512`, but maybe the machine that verifies the signature (with the RSA PublicKey - so it can be anyone or anything) might not be able to use something stronger than `RS256`.

In general, if you don't have a business/application/network requirement for explicitly choosing an algorithm, use the strongest key that you can and let JJWT determine the best algorithm based on the strength of that key.  Otherwise let business/application/network requirements dictate the algorithm.

In all cases however, JJWT will enforce that key lengths are the minimum mandatory lengths required by the JWT (JWA) RFC specification(s), so they're guaranteed to be safe enough to use per the specifications.

**Comment by lhazlewood** [comment]
FWIW, this is covered in our documentation 😅 : 

https://github.com/jwtk/jjwt#jws-key-create

**Comment by horizonzy** [comment]
I got it. thank you 🤭

**Comment by mrts** [comment]
@lhazlewood, I have a concern regarding `JwtParserBuilder#setSigningKey()` deprecation.

We need to validate the signature of JWTs with a public key from the certificate that is embedded in the JWT header `x5c` field (as specified in [RFC 7515](https://tools.ietf.org/html/rfc7515#section-4.1.6)).

When `setSigningKey()` is present, we can first parse the header without specifying the key and set if after it becomes available:
```java
var parser = Jwts.parserBuilder()
                 .setAllowedClockSkewSeconds(allowedClockSkewSeconds)
                 .build();
var header = parser.parse(jwt.substring(0, headerEnd)).getHeader();

... validate header fields and avoid parsing the body in case they are invalid ...

var certificate = parseCertificate(header.get("x5c"));
parser.setSigningKey(certificate.getPublicKey());
parser.parseClaimsJws(jwt);
```

In case `setSigningKey()` is deprecated, we need to re-create the parser in the last step for signature validation:

```java
var certificate = parseCertificate(header.get("x5c"));
Jwts.parserBuilder()
    .setSigningKey(certificate.getPublicKey())
    .build()
    .parseClaimsJws(jwt);
```

What are your thoughts regarding this?

**Comment by lhazlewood** [comment]
Hi @mrts !

There are a couple of issues with the `JwtParserBuilder#setSigningKey`* method variants.

1.  The key a parser uses isn't _really_ a signing key.  Technically it is a signature _verification_ key.  It is for legacy reasons that JJWT calls it a 'signing' key for both building and parsing.  This is incorrect and a proper name (verification key) will be used for 1.0.

That said, this particular issue has nothing to do with your question 😅 , so I'll address the more relevant answer next.

2.  The `JwtParserBuilder#setSigningKey`* methods are only to be used when you have a static key configured that will always be used to verify any token parsed by that parser.  For simple applications, this can always be the same, but it's not exactly recommended.  Keys ideally should be rotated, changed, etc over time to reduce exposure to attacks.  That's a little harder to do with statically-configured keys (it's not terrible though: you can create two parsers - one with the old key, one with the new key.  Parse with the new one first, and if that fails, fall back to the old.  That's just one key rotation strategy.  Applications will define others based on need).

Ideally, it's better to dynamically, at runtime, determine the verification key to use for any given signed JWT, look that up, and then verify the signature with that.  That's exactly what your use case is - you need to inspect the header, find the appropriate public key, and use that for signature verification.

This use case is why the `SigningKeyResolver` was created (again, a legacy term.  In v 1.0, we'll call this a VerificationKeyResolver or similar.  Implementing and configuring a key resolver on a parser allows you to inspect the header and return the appropriate verification key, and JJWT will use that to verify the signature automatically.  This is covered in documentation here:

https://github.com/jwtk/jjwt#verification-key

and specifically https://github.com/jwtk/jjwt#signing-key-resolver

I hope that helps!

**Comment by mrts** [comment]
Hi @lhazlewood ! Thank you! Can I vote for `@FunctionalInterface` for the upcoming `VerificationKeyResolver`(s) so that lambdas can be used?

It would be awesome if I could write something along the lines of the following:

```java
var parser = Jwts.parserBuilder()
                 .setVerificationKeyResolver((header, claims) ->
                                                 parseCertificate(header.get("x5c")).getPublicKey())
                 .build();
parser.parseClaimsJws(jwt);
```

**Comment by lhazlewood** [comment]
@mrts the last release just prior to 1.0 final will probably still be JDK7-compatible, so no `@FunctionalInterface` at that time.  The 1.0 release that immediately follows is likely to be JDK 8-based, but we're still looking into that because there are still a lot of Android apps that don't support 8 yet.

That said, the new interface will be functional, but it will change slightly:  instead of passing in both the header and the claims, it will likely just pass in the header.  There are a number of scenarios where it is better (e.g. better performance, safer, etc) to parse the body/claims only after signature verification.  People shouldn't be putting in key identifiers in the body anyway - that's why `kid` (and `x5c`, etc) header parameters exist - so there's no real reason to inspect the body to find the appropriate key - just the header.

Cheers!

**Comment by mrts** [comment]
> There are a number of scenarios where it is better (e.g. better performance, safer, etc) to parse the body/claims only after signature verification. People shouldn't be putting in key identifiers in the body anyway - that's why kid (and x5c, etc) header parameters exist - so there's no real reason to inspect the body to find the appropriate key - just the header.

Perfect, that's exactly our thinking as well.

Heartfelt thanks for your good work and careful design of the API - and likewise, cheers!

**Comment by Marcono1234** [comment]
Slightly unrelated to this issue, but @mrts, when using `"x5c"` for signature validation you have to verify the ceritificate chain for that certificate, as mentioned in [RFC 7515](https://tools.ietf.org/html/rfc7515#section-4.1.6) you linked:
> [...] The recipient MUST validate the certificate chain according to RFC 5280 [RFC5280] and consider the certificate or certificate chain to be invalid if any validation failure occurs.

Otherwise a user can sign a token with their own private key, provide their public key as `"x5c"` and the token would be pass verification.
I assume that you have left this out because it is not directly related to this issue, but it might be important for future readers.

**Comment by mrts** [comment]
> Slightly unrelated to this issue, but @mrts, when using "x5c" for signature validation you have to verify the ceritificate chain for that certificate, as mentioned in RFC 7515 you linked:

Thanks for bringing this up, absolutely!

Here's how we do it in the [Web eID project](https://web-eid.eu/): [link](https://github.com/web-eid/web-eid-authtoken-validation-java/blob/main/src/main/java/org/webeid/security/validator/validators/SubjectCertificateTrustedValidator.java#L49-L79).
