### ISSUE TITLE
jjwt library not allow explicitly to specify hashing algorithm during token validation

### ISSUE THREAD

**Issue by salman-khandu** [jwtk/jjwt#641]
Is there any way to specify the hashing algorithm while validating the token explicitly? OWASP cheatsheet suggests to specify it explicitly as best practices.

`Jwts.parser().setSigningKey(key).parseClaimsJws(token);`

I have tried to find a way but I haven't found it. auth0 library https://github.com/auth0/java-jwt allow adding algorithm during token validation.

**Comment by lhazlewood** [comment]
This is unnecessary with JJWT because the `None` algorithm - as well as using weaker or different signature verification keys - has always failed with JJWT signature verification since JJWT was first released.  Auth0's initial releases of `java-jwt` suffered from this security flaw, which is why they had to add support for it.  There's no reason to add it to JJWT that I can tell.  I'm happy to discuss further and even enhance the library if you can demonstrate a use case that JJWT cannot satisfy though!

**Comment by lhazlewood** [comment]
Closing for now - happy to re-open if you can demonstrate a case where JJWT doesn't satisfy best practices already.

**Comment by er4z0r** [comment]
@lhazlewood sorry to bring this up again. I just ran into JJWT v0.11.2 on a pentest an was also looking at this issue. Can you point me to where in the source NONE is prevented?

**Comment by lhazlewood** [comment]
@er4z0r `NONE` isn't explicitly prevented, but this logic has changed significantly in the `jwe` branch, which I hope to have out in a week or so:

https://github.com/jwtk/jjwt/blob/5307aa10ffe9aca8316efa6348ff712383048dea/impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java#L445-L488

**Comment by er4z0r** [comment]
Indeed it is much more obvious and readable in the new code. Still don't get why the old code in 0.11.2 doesn't seem to be susceptible to none/signature exclusion.
