### ISSUE TITLE
Security Patches are not released to Maven Repository

### ISSUE THREAD

**Issue by bibAtWork** [jwtk/jjwt#715]
**Describe the bug**
The latest released version on the [Maven Repository](https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson) is 0.11.2 at 11.06.2020. Mutliple security patches haven been applied since than, but never have been released.

**To Reproduce**
1. Go to [Maven Repository](https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson)
2. Click on latest version 0.11.2

**Expected behavior**
A stable state of the artifact should also be relased to Maven

**Screenshots**
![image](https://user-images.githubusercontent.com/57631430/159740065-24f38beb-b4bf-435b-a370-d7dee2bfcf82.png)

**Comment by anahita-arora** [comment]
Hi team,
When can we expect the patches to be released to maven? Also, please clarify, will these patches resolve the vulnerability marked in maven?
Maven - https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl/0.11.2
Vulnerability - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15522

**Comment by lhazlewood** [comment]
You should always use Maven Dependency Exclusions and specify the version(s) you prefer in your project if a library (like JJWT) does not cut a release as quickly as you would like: https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#dependency-exclusions

You always have control over transitive dependencies - there is no need to wait for a library to cut a release in order to change their transitive dependencies.

That said, we'll be addressing these concerns in a patch release shortly.  It just hasn't been as high as a priority as focusing on the `jwe` branch, given app developers can control JJWT's transitive dependencies themselves.

**Comment by lhazlewood** [comment]
FWIW, this change has already been made to master and will be released with the next release.
