### ISSUE TITLE
Parsing multiple claims with a custom claim type 

### ISSUE THREAD

**Issue by denissignoretto** [jwtk/jjwt#718]
With reference to the possibility to parse a custom/private claim [1], is not clear to me whether is already possible or not having the deserialization of multiple custom/private claims, each with it's own POJO object/structure.

e.g.

```
{
    "issuer": "https://example.com/issuer",
    "https://example.com/user": {
      "firstName": "Jill",
      "lastName": "Coder"
    }
   "https://example.com/office": {
      "name": "My Office",
      "street": "19th street Avenue"
    }
}
```

[1] - https://github.com/jwtk/jjwt#parsing-of-custom-claim-types

**Comment by lhazlewood** [comment]
The first code snippet in the referenced link shows a Map builder being used to create a ‘Map’ of claim name-to-type mappings to use as the `JacksonDeserializer` constructor:

```
Maps.of("user", User.class).build()
```

Just add more than one name-value pair 😉

Also, if possible, please ask questions as covered here: https://github.com/jwtk/jjwt#help-questions, as we use Github Issues for actionable work on the codebase itself.  Thanks!

**Comment by sysmat** [comment]
- documentation https://github.com/jwtk/jjwt#parsing-of-custom-claim-types  is not forking for **version 0.11.5**
- there is no json method

**Comment by sysmat** [comment]
there is no version 0.11.5, documentation is totaly broken

```java 
Maps
    .of("https://example.com/user", User.class)
    .of(“https://example.com/office”, Office.class)
    .build()
```

**Comment by ediccar** [comment]
Take a look at the javadoc here https://github.com/jwtk/jjwt/blob/master/api/src/main/java/io/jsonwebtoken/lang/Maps.java#L35
The example shows how to chain together multiple custom claims.

```
 Maps
    .of("https://example.com/user", User.class)
    .and(“https://example.com/office”, Office.class)
    .build();
```

**Comment by lhazlewood** [comment]
@sysmat that's because the `master` branch currently contains code that has been merged and is awaiting release, but we haven't cut the release yet.  In the future we're not going to merge not-yet-released code to `master` because of this confusion.

That said, you can (and should) always find the relevant documentation for a specific version by looking at tags.  And not just with JJWT, but with any GitHub-hosted open source project:

![image](https://github.com/jwtk/jjwt/assets/121180/33db19d0-2caa-4a5d-9a92-1e11e23f73eb)

A tag will always reflect the documentation for that specific version.

**Comment by sysmat** [comment]
@lhazlewood thx, my mistake, I was just following the link in error exception
