### ISSUE TITLE
JVM Vulnerabiliity CVE-2022-21449

### ISSUE THREAD

**Issue by prashil-sophos** [jwtk/jjwt#726]
used https://github.com/jfrog/jfrog-CVE-2022-21449 to check for our microservice and found that jjwt-0.9.1 might be vulnerable. Can you please confirm which version should we upgrade to if available for this CVE?

In build/libs/<microservice>.jar/BOOT-INF/lib/jjwt-0.9.1.jar/io/jsonwebtoken/SignatureAlgorithm.class: potential use of ECDSA - may be vulnerable

**Comment by dhd0004** [comment]
I can confirm that jjwt 0.11.2 is vulnerable.
This JWT will pass all checks:
eyJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJCb2IifQ.**MAYCAQACAQA**

**Comment by lhazlewood** [comment]
JJWT is not vulnerable - the _JVM_ itself is vulnerable, and _only_ if you are running Java SE versions 15-15.0.6, 17-17.0.2, or 18.

If you are running one of these JVM versions, the 'correct' fix is to upgrade to 15.0.7, 17.0.3 or 18.0.1 respectively.  This is because even if you upgrade JJWT, anything else that uses ECDSA signatures (your own application code, other 3rd party libraries) would still be vulnerable.  That is, upgrading JJWT doesn't fix the root cause of the problem.

Now - all of that being said, we are in the process of releasing 0.11.3 that does provide additional security guards to address CVE-2022-21449, even on vulnerable JVMs.  But again, this only makes things nicer for JJWT, and doesn't address the root cause of the problem if it exists anywhere else in your code or libraries.

**Comment by lhazlewood** [comment]
@dhd0004 That may be true, but it's a false sense of safety - just because it doesn't surface through one library doesn't mean it is solved in all places - it may exist in another library or within application code or in a web server or the networking stack, etc.

Regardless of the upcoming 0.11.3 release, everyone who uses those JVM versions are vulnerable until they upgrade the JVM.  It's simply not good enough to assume an app is safe just by upgrading just a JWT library.  TLS negotiation (for example) could be vulnerable as well (among other things).

**Comment by lhazlewood** [comment]
The other benefit of upgrading the JVM instead of any library is that you just don't have to change your application code - no changing project files, pulling in new dependencies, rebuild and re-release your software, etc.  You can just swap out the JVM and you're safe against this particular vulnerability.

This is **so** much easier for most application teams than trying to track down any code where this problem might exist and then individually upgrading each one and cutting a new release, etc.

**Comment by lhazlewood** [comment]
Resolved by the 0.11.3 release.  Please allow 30 minutes or so for it to appear in Maven Central.
