### ISSUE TITLE
Vulnerabilities from dependencies CVE-2022-42004 CVE-2022-42003 version: 0.11.5

### ISSUE THREAD

**Issue by JasonTheDynamite** [jwtk/jjwt#758]
Please fix ASAP

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/18309065/196180330-cb1f6c69-e470-483b-aa41-7ceaf518580a.png">

**Comment by BenanaH** [comment]
```xml
<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt</artifactId>
    <exclusions>
        <exclusion>
            <artifactId>jackson-databind</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
        </exclusion>
    </exclusions>
</dependency>
```
It work for me.
Maybe this method will help you.

**Comment by bdemers** [comment]
@BenanaH it looks like you are still on an old version of JJWT?
Take a look at the current version's dependencies:
https://github.com/jwtk/jjwt#maven

**Comment by lhazlewood** [comment]
Just a note for anyone that might have a similar issue:

You always have control over transitive dependencies.  If a project (JJWT, Spring, etc) doesn't update it's internal transitive list quickly enough for your preferences, you can always use Maven's Dependency Exclusion concept to exclude a library's default transitive dependency:

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#dependency-exclusions

and then declare that transitive dependency in your project explicitly.

Given how many CVEs Jackson has been having this last year, it might be better for JJWT to declare that as a `provided` dependency so that projects must always declare Jackson explicitly and not rely on JJWT's transitive association.  That wouldn't be the "Maven Way" however, so I'm not sure it'd be a good idea.

That said, in this case, it's better to exclude and then declare your own in situations like this.
