### ISSUE TITLE
.parse method behaviour is misleading

### ISSUE THREAD

**Issue by knyttl** [jwtk/jjwt#775]
**Describe the bug**

Consider following code:

```kotlin
Jwts
    .parserBuilder()
    .setSigningKey(publicKey)
    .build()
    .parse(jwtString)
```

This code looks nice and safe, however it is completely hidden that the JWTs without signature will be correctly accepted. We had a major security issue because of this as one should use `.parseClaimsJws` instead.

**Proposal**

1. Rename `.parse` method to something like `.parseWithoutSignature`.
2. Disallow using `.parse` once the `.setSigningKey` is used.

**Comment by lhazlewood** [comment]
This is documented and expected behavior, and is relied upon by many applications, especially those in private network environments.  For what it's worth, nothing in JJWT's public documentation suggests calling `parse` - every example uses `parseClaimsJws`.

That said, the default behavior is changing on our next release because some developers can be confused as you intimated, _and_ the JWT specifications have been changed - after JJWT was created and released - to change the default behavior and disallow unprotected parsing by default.

For posterity, I commented on this in https://github.com/jwtk/jjwt/pull/658#issuecomment-1101614067.  The second code block in that comment shows the changed behavior - it's disabled by default, but private network environments can explicitly re-enable it if desired (and hopefully reading the documentation that explains the security repercussions of doing so).

Anyway, I'm closing this only because the functionality is already implemented in the `jwe` branch - it'll be in the next minor release :)
