### ISSUE TITLE
Simple code hangs on .signWith

### ISSUE THREAD

**Issue by raszkiewicz** [jwtk/jjwt#778]
Just a basic Java code for my Spring Boot app to check how it works:

```
    private String doGenerateJWT(Map<String, Object> claims){

        Date expiration = new Date(System.currentTimeMillis() + JWT_TOKEN_VALIDITY * 1000);

        return Jwts.builder()
                   .setHeaderParam("kid", apiKey)
                   .setClaims(claims)
                   .setExpiration(expiration)
                   .signWith(SignatureAlgorithm.HS256, "test123")
                   .compact();
    }
```

is implemented as the `@Component` and then `@Autowire` to my controller.

It will work fine for testing but when I will run the app it will hang on `.signWith()` step.

Any thoughts?

**Comment by bdemers** [comment]
What version of JJWT and Java are you using?

At first glance (assuming your key is "test123"), I would expect that line to fail to parse the base64 encoded key, or fail due to the key being too short. Both of those conditions should throw an exception.

Assuming you are using the latest version of JJWT, and it's hanging, can you take a thread dump?

**Comment by raszkiewicz** [comment]
Got some examples from the Internet which are using 0.9.1 and as you have suggested - update it to the most recent, changed code and used 

`SecretKey key = Keys.hmacShaKeyFor(Decoders.BASE64.decode(encodedSecretString));`

fixed my issuse

**Comment by bdemers** [comment]
Thanks for following up @raszkiewicz!
