### ISSUE TITLE
Unable to map object stored in Subject Claim to Java Class

### ISSUE THREAD

**Issue by jaredr-branscum** [jwtk/jjwt#788]
**Describe the bug**
Using 0.9.1 from Maven Repository, Claims.parse strips the quotation marks from the subject claim. I have a use-case where I need the subject claim to be a JSON object that's not stringified in the decoded JWT payload. This prevents me from being able to use an Object mapper to map the string of the subject claim to a Java class.

**To Reproduce**
Create a HS256 signed JWT with this decoded payload:
```
{
  "sub": {
             "something": "thing"
             }
}
```

Call a secure endpoint with the JWT in the header

Get the claims using the JWTS parser
Attempt to map the object to a Java Record using a plain ObjectMapper.readValue(subjectClaim, SomeJavaClass.class)

**Expected behavior**
Some Java Class stores object contents of subject claim

**Actual behavior**
Json processing exception is thrown because the field and value parameters of the subject claim were stripped of their quotation marks.

The log will show that the string stored from Claim claim.getSubject() looks like: {something=thing} when it should be {"something"="thing"}

**Note**
I am aware of the RFC https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2
But my hands are tied with finding a bugfix but not having control over the structure of the decoded payload.

**Comment by lhazlewood** [comment]
Hi there,

I'm not sure I follow what you mean by `stripped of their quotation marks`, JJWT doesn't do that, but maybe the `ObjectMapper` does?

Also, FWIW, the latest release version of JJWT is 0.11.5, and 0.9.1 is reasonably far behind: https://github.com/jwtk/jjwt/tree/0.11.5.

Anyway, this is tricky - whoever is generating that `sub` claim is violating the RFC specification, and we're not willing to change the JJWT implementation to violate the spec (i.e. `sub` is defined to be a `StringOrURI` only).  But you might be able to perform a workaround.

One potential workaround is provide an ObjectMapper that, when it sees the `sub` field, takes the mapped JSON object and turns it into an inner JSON string.

Then you can call `wt.getClaims().getSubject()` and then parse that String to a JSON object yourself.

Another potential solution is to use the ObjectMapper to dynamically 'swap' out what the `sub` value and switch it to a different mapping entry.  That is, if you see a `sub` key, and that value is an Object (not a String), then instead of representing the value as `sub`, return it as `subject` or something similar.  Then you can do `jwt.getClaims().get("subject)"`.

You could also provide your own `Serializer` to JJWT's Parser and that `Serializer` implementation replaces the `sub` entry for a `subject` entry instead (with a JSON Object value).

Hopefully this gets some ideas flowing!

**Comment by jaredr-branscum** [comment]
Thanks for the quick response @lhazlewood. For clarification, 
stripped of quotation marks means that the " symbol used in the JSON payload is removed from the subject claim object.
Here's an example payload:
```
{
  "sub": {
  "someField": "someValue"
  }
}
```
Default Secret (non-encoded): your-256-bit-secret
Encoded JWT:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsic29tZUZpZWxkIjoic29tZVZhbHVlIn19.6Lm78AsND75Vv7JRV9k7CHSvC5aVN2vQ79HEU1z0_YE`

The logger shows this value for the claim object:
`sub={somefield=someValue}`
But it should log this:
`sub={"somefield"="someValue"}`

This logs prior to using the object mapper and is directly logging what's returned from the Jwts.parser().someMethods().getBody() so this library or some serializer is removing the quotation marks from the object.

**Comment by lhazlewood** [comment]
I looked into this a little more, I think that's just a change in the logging/toString output and not the actual JSON library functionality.

Out of curiosity, why does it matter if JJWT's log format has quotes or not?  Java `toString()` output is not guaranteed to be structured, and JJWT (and the majority of Java libraries for that matter) make no guarantee on API-compatibility with log/text output - the actual `Jwt` structure is what (usually) matters for application development.

FWIW, since Claims are JSON, you could log it via any JSON library. For example, using Jackson:

```java
Claims claims = claimsJws.getPayload();
String json = new ObjectMapper().writeValueAsString(claims);
logger.log(json);
```

**Comment by lhazlewood** [comment]
Just a follow-up note about the above Claims JSON logging example:

The above is fine *only* if `Claims` does not have any sensitive/secure information in it.  With encrypted JWTs (i.e. JWEs), the payload could have very sensitive information (credit cards numbers, home addresses, etc), and it would be a very bad idea to blindly convert them to full unencrypted JSON and log that.

This is why with the JJWT's new JWK (JSON Web Key) support, any `toString()` output will only print `<redacted>` string literals for private/secret fields, because the security risk would be very high otherwise.

**Comment by lhazlewood** [comment]
@jaredr-branscum while the custom type approach for a standard claim works for `0.9.1`, it won't for `0.12.0` or later - all RFC standard claims will enforce correct data types during serialization/deserialization and reject malformed JWTs.  But even so, the workarounds for the custom JSON parser (where you swap out the `sub` value for a string version and then change it into a Java object upon calling `claims.getSubject()`) will work.  The RFC-compliant answer however is to use a different claim that doesn't conflict with these: https://www.iana.org/assignments/jwt/jwt.xhtml

> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsic29tZUZpZWxkIjoic29tZVZhbHVlIn19.6Lm78AsND75Vv7JRV9k7CHSvC5aVN2vQ79HEU1z0_YE

I base64url-decoded the payload (`eyJzdWIiOnsic29tZUZpZWxkIjoic29tZVZhbHVlIn19`) and this is what I get:

`{"sub":{"someField":"someValue"}}`

which looks totally normal.

JJWT doesn't modify the payload at all - it just sends it right into the JSON deserializer, so I can't see how anything would modify it.

Do you have a short test case (Java `main` method, anything) that can re-create the behavior on `0.11.5` ?

> adding the jackson serializer makes the escaped JSON string version of the payload return an error.

This is why I'm confused - Jackson is the default JSON processor for JJWT, I can't see how you'd be getting different results.

That said, `0.9.1` has long been deprecated and is no longer supported (it's almost a 5 year old release).  If you can reproduce it on `0.11.5` or the current `master` branch (I am unable to), I'd be happy to fix any problems.

**Comment by lhazlewood** [comment]
Closing since the upcoming `0.12.0` release will reject any `sub` value this not a String, because anything other than a String violates the RFC mandatory data type (and will result in a MalformedJwtException in `0.12.0`).

There is still a way to do this if you want, even in `0.12.0`: encode your java object into a JSON String (not a JSON Object) and set that as the `sub` value, and then when you obtain the `sub` string, decode the JSON String into a Java object.
