### ISSUE TITLE
Haven't implemented jjwe yet? There is no `encryptWith()` method in `Jwts.builder()`, the version is 0.11.5

### ISSUE THREAD

**Issue by yinyicao** [jwtk/jjwt#789]
The example in this doc I can't run: https://github.com/jwtk/jjwt#creating-a-jwe

**Comment by Polleke007** [comment]
I have the same problem, could it be the issue that the latests release not is build with version 0.11.5? 
If you unzip the latests release there is no `encryptWith()` method,

The same is for maven, the .m2 folder contains the latest version 0.11.5 but if you decompile the `JwtBuilder` there is once again no `encryptWith()` method.

**Comment by lhazlewood** [comment]
The main branch always reflects all work that has been merged but not yet released (like the jwe work).  `0.11.5` is the current/latest release, and documentation is available via the tag associated with that release, e.g. https://github.com/jwtk/jjwt/tree/0.11.5.

We're actively trying to wrap up outstanding items for the `0.12.0` release which will include all the JWE and JWK work.  I hope that helps!

**Comment by Polleke007** [comment]
@lhazlewood do you have a timeline when you expect the jwe will be available?

**Comment by lhazlewood** [comment]
@Polleke007 unfortunately no since we work on this in-between professional (paid) work, and that necessarily takes precedence.  I will say however that the 0.12.0 / JWE release is my highest open-source priority, and I'm actively working on it - I spent about 8 hours on code and documentation work to prepare for the release, and I probably have another few days of work left.  Just getting uninterrupted time can be a little difficult sometimes 😅

**Comment by lhazlewood** [comment]
Still working on it! And _very_ heavily - the PKCS11 (SmartCard / HSM) testing took a full week and a half and bumped everything back.  That said, all of my work time is dedicated to getting this release out - probably 90+ hours of work in the last two weeks alone.  Again, I can't provide a timeline, but this is my highest priority.  I'm basically working on only this until it's finished.
