### ISSUE TITLE
package jjwt is not resolved

### ISSUE THREAD

**Issue by gocodersuresh** [jwtk/jjwt#885]
**Describe the bug**
io.jsonwebtoken package does not exist. i have tried below dependency used intelij or simple command line mvn clean install
still this does not work.

**DONT CLOSE this issue saying as duplicate as resolved it does not work despite being reported earlier you never cared to resolve this issue **

**To Reproduce**
add these dependancy in the pom.xml
 <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-security</artifactId>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>0.11.5</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>0.11.5</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId> 
                <version>0.11.5</version>
                <scope>runtime</scope>
            </dependency>
            

- do reolod of project in intelij
- or do mvn clean install
- still you cant see io.jsonwebtoken package imported 
- 
**Expected behavior**
you should be able to use jwts and other classes
![Uploading Screenshot 2023-12-26 220546.png…]()

**Screenshots**

**Comment by lhazlewood** [comment]
Hi @gocodersuresh !

Just in the spirit of friendly communication, the following comes across (feels) very rude and demanding:

> **DONT CLOSE this issue saying as duplicate as resolved it does not work despite being reported earlier you never cared to resolve this issue **

A simple "Please" or other kindness goes a long way in getting purely unpaid volunteers (the JJWT developers) to help you.

Anyway, we are unable to reproduce this issue, because it does indeed work for sample projects that we try.  Also, for some reason, the screenshot you tried did not upload, so we can't see it (GitHub does not show it).

Do you have a small sample/test maven project that you could make publicly available in GitHub that we can clone and test locally? I am happy to help, but I am unable to reproduce the behavior you describe.  I need at least a starting point that shows what problem you're experiencing.

**Comment by lhazlewood** [comment]
@gocodersuresh we haven't heard from you since my last comment.

Do you have a simple example project that helps us try to re-create the problem you're seeing?

**Comment by gocodersuresh** [comment]
Got busy with work will share with you

**Comment by lhazlewood** [comment]
Just doing a little housekeeping: I'm marking this as stale, and it will be closed unless an example/test project can be provided.

Note that if you're having issues with multiple dependencies, you can try just the 'single jar' `jjwt` dependency.

**Comment by lhazlewood** [comment]
Closing due to 6 month inactivity.
