### ISSUE TITLE
Unable to access jcaName from Jwts.SIG

### ISSUE THREAD

**Issue by ChiragPatelDotmatics** [jwtk/jjwt#915]
**Describe the bug**
Unable to access jcaName from Jwts.SIG

**To Reproduce**
We use SignatureAlgorithm to get the jcaName i.e. SignatureAlgorithm.HS256.getJcaName().

As of 0.12.0 SignatureAlgorithm is deprecated and the documentation advises to use Jwts.SIG.

However the method to getJcaName is not public in CryptoAlgorithm.java

**Expected behavior**

The method getJcaName should be public in CryptoAlgorithm.java and we should be able use Jwts.SIG to get the jcaName i.e. Jwts.SIG.HS256.getJcaName.

**Screenshots**

SignatureAlgorithm deprecated:
![image](https://github.com/jwtk/jjwt/assets/158115232/341ab4ec-0e36-4f03-8205-b457cc1fe3cd)

getJcaName in CryptoAlgorithm.java:
![image](https://github.com/jwtk/jjwt/assets/158115232/39f36ae9-3d0f-4ed0-a3b0-4b05b8401d85)

**Comment by lhazlewood** [comment]
Hi @ChiragPatelDotmatics !

This is because the concept of a JCA name isn't relevant for JJWT's public API: it's not something an application developer would ever need to specify to create or parse JWTs or JWKs.

As such, it is an 'implementation detail' of individual Algorithm implementations, not something that should be exposed to parts of the API that never need it.

Additionally, not all algorithms use a single JCA name or have a direct equivalent.  For example, the JJWT-internal `ConcatKDF` algorithm implementation doesn't have a JCA name - only an indirect 'helper' hash algorithm name.  Also, certain AES algorithm implementations don't have a 1:1 equivalent to a single JCA name.  Sometimes there are two internal JCA names (one for the Cipher transformation string, another for the KeyGenerator, etc).

So it'd be difficult to 'force' a single `getJcaName()` on every algorithm concept that would make sense for general use cases for application developers, and not something we want to force on implementations unnecessarily.  Especially custom implementations, since it'd never used by JJWT outside of an algorithm implementation anyway.

For all of these reasons, I don't see a strong reason to add it to the new (> 0.12.0) public Algorithm interfaces.  Especially since it would cause an implementation/maintenance burden for the JJWT team for something that isn't needed for JWT or JWK use cases.

That said, it appears the reason you want to do this is to support the following method:

```java
private static SecretKey generateSigningKey(String secret);
```

So I have a couple of concerns/questions that hopefully you'll find helpful:

1.  Using `string.getBytes()` is almost always incorrect in a cryptographic/security context.  See the following link for more information, as well as the `Warning` section directly below it: https://github.com/jwtk/jjwt?#jws-create-key-secret

2. Will the `Keys.hmacShaKeyFor` utility method work for you instead?  For example:
    
    ```java
    private static SecretKey generateSigningKey(String secret) {
        // calling secret.getBytes() is odd because standard alphabet strings often
        // have poor entropy. It would be better if the secret was a Base64Url-encoded
        // totally random byte array that could be decoded instead:
        return Keys.hmacShaKeyFor(Decoders.BASE64URL.decode(secret));
    }
    ```

3. If those don't work, you could always fall back to calling `Jwts.SIG.HS256.key().build().getAlgorithm()`, but again, this feels weird/incorrect: if `secret` is stored somewhere, its metadata (e.g. JCA name) should be stored with it also so the key can always be re-created exactly as intended, even if application code changes, instead of using a JJWT implementation detail.
    
    (Or, for example, store it (securely, encrypted) as a Secret JWK instead so it can easily be re-created with a `Jwks.parser()` builder).

**Comment by ChiragPatelDotmatics** [comment]
Hi @lhazlewood,

Thanks you for your comprehensive reply.

We can use Keys.hmacShaKeyFor(secret) so all resolved.

Thanks again!
