### ISSUE TITLE
Perform other validations before signature validation

### ISSUE THREAD

**Issue by lhazlewood** [jwtk/jjwt#92]
As discussed in #86, the SigningKeyResolver might require a network hop.  It would be more efficient to do the other validations first before invoking the SigningKeyResolver to ensure that if the other validations fail, a network hop isn't ever executed.

This issue represents the work to ensure all validations execute first before finishing with signature validation.

**Comment by josebarrueta** [comment]
Just my 2 cents here, I think one of the reasons I proposed to do all other validations after the signature is verified is because it's the only way to ensure that you can trust the content of the body.

I understand there are users that want to avoid a network hop to look for a key in a datastore or do a extra computing if the body has a invalid field, but we need to make sure this change doesn't affect other users that are relying in the current behavior (which I think is useful).

**Comment by lhazlewood** [comment]
Good point!  Need to think then if this should be implemented.

**Comment by lhazlewood** [comment]
Agreed that signatures must be validated before other fields can be validated since you can't validate fields that are not yet trusted.
