### ISSUE TITLE
Support of Ed25519 Keys and Signatures from the libSodium Library

### ISSUE THREAD

**Issue by alexkeramidas** [jwtk/jjwt#94]
Congrats for your good work. In an application that we are developing now, we use the libSodium library, specifically the Ed25519 algorithm to produce, sign and verify keys.

- https://github.com/jedisct1/libsodium (C library)
- https://github.com/joshjdevl/libsodium-jni (JNI binder)

To our knowledge JJWT does not support that algorithm and uses as keys [for signing and verifying] the native Android Key class.

We want to use our own Ed25519 keys to sign and verify the JWTs. Is there any possibility of you implementing such a functionality. If not, do you have any suggestions on which classes should we extend to make the JJWT lib accept our own keys and sign the JWTs with em?

Thank you in advance.

**Comment by lhazlewood** [comment]
Hi @alexkeramidas 

Thanks for the kudos!

ed25519 is not a [JWA](https://tools.ietf.org/html/rfc7518) spec-compliant algorithm, so JJWT does not currently support it.

That said, I think we'd be willing to do so if you can submit a pull request for the work and we *clearly* label anywhere it is referenced that it is not a specification-supported algorithm, and that people should use it at their own risk accordingly.

To do this like the other algorithms you'd need to do the following:

1. Add an enum value to `io.jsonwebtoken.SignatureAlgorithm` that represents your algorithm.
2. Implement the `io.jsonwebtoken.impl.crypto.Signer` interface to compute signatures according to your algorithm.  An instance of this interface is used to create signatures for JWTs.  See the `EllipticCurveSigner`, `MacSigner` and `RsaSigner` implementations for examples.
3. Modify the `io.jsonwebtoken.impl.crypto.DefaultSignerFactory` to return a new instance of your `Signer` implementation based on the `SignatureAlgorithm` and `Key` arguments.
4. Implement the `io.jsonwebtoken.impl.crypto.SignatureValidator` interface to perform signature validations.  See the `MacValidator`, `RsaSignatureValidator`, and `EllipticCurveSignatureValidator` implementations for examples.  An instance of this interface is used to validate signatures of existing JWTs.
5. Modify the `io.jsonwebtoken.impl.crypto.DefaultSignatureValidatorFactory` implementation to create a new instance of your SignatureValidator implementation based on the `SignatureAlgorithm` and `Key` arguments.

Note that `EllipticCurveSigner` and `EllipticCurveSignatureValidator` both extend from a parent abstract class named `EllipticCurveProvider` which itself extends `SignatureProvider`.  This is done because both signature calculation and signature validation share common concepts and some logic, so the abstract classes exist to simplify the Signer and Signature Validator implementations, respectively.  `RsaSigner` and `RsaSignatureValidator` do the same by extending `RsaProvider`.  If your algorithm has similar logic that can be shared, please follow the same design approach.

Finally, our build enforces 100% code coverage for all code via the cobertura maven plugin.  Ensure you write lots of tests to guarantee this coverage percentage! :)  if for some reason, you can't get it to reach 100% (there are some rare occasions when cobertura can't detect 100% due to its inability to inspect the byte code in all cases, e.g. w/ generics), please discuss here and we'll see if we can either fix the problem or drop the threshold assertion for that one class (e.g. to 99 or 98 percent).

I look forward to a PR! :)

**Comment by alexkeramidas** [comment]
Thank you very very much!
We will start working on it and as soon as we are happy with the results (even if some tests fail) we will notify you about the progress and/or if some help will be needed. So you can close this issue until we come back to you with results!

**Comment by lhazlewood** [comment]
Sounds good!

**Comment by alexkeramidas** [comment]
All right got down to it today. The main difference is that we use sodium generated keys whereas the library uses normal java keypairs.

Also we want to generate the keys out of sodium so no need to make an Ed25519 provider for that purpose. 

Anyway after 4-5 hours I managed to produce a correct (and verifiable via a python app we use) JWT using something like that

`Jwts.builder().setHeader(jwtHeader).setClaims(jwtPayload).signWith(SignatureAlgorithm.ED25519, signingKey).compactSodium();`

To achieve that I changed the following files:

## _Altered files_

>**Enums**

- io.jsonwebtoken.SignatureAlgorithm

>**Interfaces**

- io.jsonwebtoken.JwtBuilder

>**Classes**

- io.jsonwebtoken.impl.crypto.DefaultJWTBuilder
- io.jsonwebtoken.impl.crypto.DefaultSignerFactory

## _New Files_

>**Intefaces**

- io.jsonwebtoken.impl.crypto.SodiumSignerFactory
- io.jsonwebtoken.impl.crypto.SodiumSigner

>**Classes**

- io.jsonwebtoken.impl.crypto.SodiumJWTSigner
- io.jsonwebtoken.impl.crypto.EdwardsCurveSigner

For some reason I cannot seem to make the **`Base64codec`** class work. The javax.xml.bind.DatatypeConverter is not recognized and I couldn't find a working gradle dependency to use. So I used the Base64 android class which with the correct flags seems to do the job (any suggestions?).

No tests written for now as I need to do the verify part but I thought I should let you know.

**Comment by lhazlewood** [comment]
Hi @Tougee - thanks for the kind words!

So I have some good news (I think) that will make this so much easier in the very near future.  I've been in the process of working on the JWE implementation(s) for the last two weeks pretty heavily, and this has spawned some refactoring and introducing new concepts that will allow you to support `Ed25519` and any other algorithm you may want:

- Per #493, the `io.jsonwebtoken.SignatureAlgorithm` enum and its usages on the builder/parser is being deprecated in favor of a new `io.jsonwebtoken.security.SignatureAlgorithm` interface.  The default RFC standard implementations of this interface will be available in a `io.jsonwebtoken.security.SignatureAlgorithms` class that simulates an enum so that code authors can reference `SignatureAlgorithms.HS256` (et. al) instead of the soon-to-be deprecated `SignatureAlgorithm.HS256`.

This addition allows you or anyone else to plugin custom `SignatureAlgorithm` implementations like `Ed25519` or any other algorithm.

- New `EncryptionAlgorithm` and `KeyAlgorithm` interfaces are being introduced in the JWE work as well with the same premise: these are interfaces, with RFC-specified default implementations, but anyone can introduce their own algorithms if the JWA RFC algorithms are not sufficient.

- A new validation framework will be introduced to allow complex validations for claims and header values, not just simple equality via (`Jwts.parserBuilder()...requireSubject("foo")`, etc), so even validation rules can be configurable.

and more.

Until they are merged, the new APIs are here:  https://github.com/jwtk/jjwt/tree/jwe/api/src/main/java/io/jsonwebtoken/security
and implementations:  https://github.com/jwtk/jjwt/tree/jwe/impl/src/main/java/io/jsonwebtoken/impl/security

As you can see, there has been a *ton* of effort put into this over the last month to fully support JSON Web Encryption (as well as cleaner JWS algorithms), and I hope to introduce these changes soon in a 0.12 or 0.13 release.

Based on this, and because of how simple it will be to add custom algorithms, it is likely that we will only create and maintain RFC-standard implementations.

I hope that helps!

**Comment by Tougee** [comment]
Sounds great! I'm looking forward this, and will deprecated out forks until it's finished
